# Image: abaco/dashboard
# Description: Web dashboard application for the Abaco (Actor Based Con(mputing)tainers platform.

FROM ubuntu:xenial

MAINTAINER Joe Stubbs <jstubbs@tacc.utexas.edu>

EXPOSE 8000

ENV DEBIAN_FRONTEND noninteractive
ENV TERM xterm

RUN apt-get update \
  && apt-get install -y python3-pip python3-dev \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
&& pip3 install --upgrade pip

RUN apt-get update && \
    apt-get upgrade -y && \
    curl -sL https://deb.nodesource.com/setup_4.x | bash - && \
    apt-get install -y build-essential python python-dev gettext nodejs xvfb chromium-browser ruby-sass uwsgi && \
    curl -SL 'https://bootstrap.pypa.io/get-pip.py' | python

RUN pip3 install --upgrade pip && pip install uwsgi uwsgitop

# RUN mkdir -p /opt/uwsgi && \
#   curl -SLk -o /opt/uwsgi/uwsgi-2.0.15.tar.gz https://projects.unbit.it/downloads/uwsgi-2.0.15.tar.gz && \
#   tar -xvzf /opt/uwsgi/uwsgi-2.0.15.tar.gz -C /opt/uwsgi && \
#   uwsgi --build-plugin /opt/uwsgi/uwsgi-2.0.15/plugins/zabbix && \
#   mkdir -p /usr/lib/uwsgi/plugins && \
#   mv zabbix_plugin.so /usr/lib/uwsgi/plugins/.



RUN pip3 install https://projects.unbit.it/downloads/uwsgi-lts.tar.gz


COPY requirements-dashboard.txt /tmp/requirements.txt

RUN pip3 install -r /tmp/requirements.txt

COPY actors /actors
COPY dashboard /abaco

WORKDIR /abaco

RUN python manage.py collectstatic --noinput

CMD ["/usr/local/bin/uwsgi", "--ini", "/abaco/conf/uwsgi.ini"]