# Test suite for abaco project.
# Image: abaco/testsuite

# inherit from the flaskbase iamge:
from tapis/flaskbase

RUN apt-get install python3-dev g++ -y

# install additional requirements for the service.
COPY actors/requirements.txt /home/tapis/requirements.txt
RUN pip3 install --upgrade pip
RUN pip3 install -r /home/tapis/requirements.txt
RUN pip3 install pytest ipython #locustio

# copy service source code
COPY configschema.json /home/tapis/configschema.json
COPY config-local.json /home/tapis/config.json

# create abaco.log file for logs
RUN touch /var/log/abaco.log

COPY actors /home/tapis/actors
RUN chmod +x /home/tapis/actors/health_check.sh
COPY tests /home/tapis/tests
RUN chmod +x /home/tapis/tests/entry.sh

RUN chown -R tapis:tapis /home/tapis /var/log
USER tapis
ENV PYTHONPATH .:*:actors:actors/*
CMD ["./tests/entry.sh"]
#entrypoint ["/tests/entry.sh"]